Initialize application.param before menubar creation
Has didn't start because app_commands.py which is loaded during menubar
creation uses shared parameters (raising AttributeError: 'Application' object
has no attribute 'param' in application.py, line 1400).

There seems to be no reason to delay the initialization of shared parameters
after menu creation and shared parameters should not depend on any other
initializations (while other initializations may theoretically need to use
shared parameters) so I decided to move them right after database connection
initialization.