Fix aggregation on table functions with zero arguments
Aggregations on table functions with zero arguments caused the following
traceback:

KeyError, Thu Aug 24 14:46:50 2023

Traceback (most recent call last):
  File "/usr/local/pytis/lib/pytis/form/event.py", line 267, in process_event
   result = system_callback()
  File "/usr/local/pytis/lib/pytis/form/event.py", line 212, in system_callback
   result = callback(event)
  File "/usr/local/pytis/lib/pytis/form/list.py", line 1301, in _on_label_paint
   value = self._aggregation_results[(cid, op)]
  File "/usr/local/pytis/lib/pytis/util/caching.py", line 69, in __getitem__
   result = self[key] = self._provider(key)
  File "/usr/local/pytis/lib/pytis/form/list.py", line 189, in _get_aggregation_result
   arguments=self._current_arguments())
  File "/usr/local/pytis/lib/pytis/data/postgresql.py", line 3101, in select_aggregate
   arguments=arguments)[0]
  File "/usr/local/pytis/lib/pytis/data/postgresql.py", line 2540, in _pg_select_aggregate
   raise_(cls, e, tb)
  File "/usr/local/pytis/lib/pytis/data/postgresql.py", line 2531, in _pg_select_aggregate
   transaction=transaction, arguments=arguments)
  File "/usr/local/pytis/lib/pytis/data/postgresql.py", line 2582, in _pg_select_aggregate_1
   return self._pg_query(query, transaction=transaction)
  File "/usr/local/pytis/lib/pytis/data/postgresql.py", line 704, in _pg_query
   outside_transaction)
  File "/usr/local/pytis/lib/pytis/data/dbapi.py", line 220, in _postgresql_query
   result = do_query(connection, query)
  File "/usr/local/pytis/lib/pytis/data/dbapi.py", line 190, in do_query
   cursor.execute(query, query_args)
KeyError: '__qarg_275'