Fix import error handling in resolver for Python 3.6+
In Python 3.6+ (the exact version number not verified) import error text may
contain additional text, such as:

ModuleNotFoundError: No module named 'pytis.form.test.printing';
'pytis.form.test' is not a package

Thus use startswith instead of equals to match those errors too...