Call argument provider even if no query_fields are defined
Some applications are actually using argument_provider which returns DB
function arguments based on some other source of information than the query
fields.  After commit 660f5066a these situations (such as Chronos.Flv in
ecomps) lead to the following traceback:

Traceback (most recent call last):
  File "/usr/local/pytis/lib/pytis/form/application.py", line 1011, in _cmd_run_form
   form = form_class(*args, **kwargs)
  File "/usr/local/pytis/lib/pytis/form/form.py", line 215, in __init__
   self.full_init()
  File "/usr/local/pytis/lib/pytis/form/form.py", line 481, in full_init
   self._full_init(**kwargs)
  File "/usr/local/pytis/lib/pytis/form/dualform.py", line 392, in _full_init
   super(PostponedSelectionDualForm, self)._full_init(*args, **kwargs)
  File "/usr/local/pytis/lib/pytis/form/dualform.py", line 372, in _full_init
   super(ImmediateSelectionDualForm, self)._full_init(*args, **kwargs)
  File "/usr/local/pytis/lib/pytis/form/dualform.py", line 102, in _full_init
   super(DualForm, self)._full_init(*args, **kwargs)
  File "/usr/local/pytis/lib/pytis/form/form.py", line 245, in _full_init
   self._create_form()
  File "/usr/local/pytis/lib/pytis/form/dualform.py", line 142, in _create_form
   self._main_form = self._create_main_form(splitter, **self._unprocessed_kwargs)
  File "/usr/local/pytis/lib/pytis/form/dualform.py", line 1276, in _create_main_form
   return self.MainForm(parent, self._resolver, self._name, guardian=self, **kwargs)
  File "/usr/local/pytis/lib/pytis/form/form.py", line 215, in __init__
   self.full_init()
  File "/usr/local/pytis/lib/pytis/form/form.py", line 481, in full_init
   self._full_init(**kwargs)
  File "/usr/local/pytis/lib/pytis/form/list.py", line 2292, in _full_init
   super(FoldableForm, self)._full_init(*args, **kwargs)
  File "/usr/local/pytis/lib/pytis/form/list.py", line 131, in _full_init
   super(ListForm, self)._full_init(*args, **kwargs)
  File "/usr/local/pytis/lib/pytis/form/form.py", line 242, in _full_init
   self._init_attributes(**kwargs)
  File "/usr/local/pytis/lib/pytis/form/list.py", line 2685, in _init_attributes
   super(BrowseForm, self)._init_attributes(**kwargs)
  File "/usr/local/pytis/lib/pytis/form/list.py", line 149, in _init_attributes
   super(ListForm, self)._init_attributes(**kwargs)
  File "/usr/local/pytis/lib/pytis/form/form.py", line 1761, in _init_attributes
   super_(RecordForm)._init_attributes(self, **kwargs)
  File "/usr/local/pytis/lib/pytis/form/form.py", line 1021, in _init_attributes
   self._init_select(async_count=True)
  File "/usr/local/pytis/lib/pytis/form/list.py", line 174, in _init_select
   result = super(ListForm, self)._init_select(async_count=async_count)
  File "/usr/local/pytis/lib/pytis/form/form.py", line 1174, in _init_select
   async_count)
  File "/usr/local/pytis/lib/pytis/form/application.py", line 1665, in db_operation
   return db_op(operation, args, kwargs, in_transaction=in_transaction)
  File "/usr/local/pytis/lib/pytis/form/application.py", line 1698, in db_op
   result = operation(*args, **kwargs)
  File "/usr/local/pytis/lib/pytis/form/form.py", line 1170, in _init_data_select
   timeout_callback=self._transaction_timeout_callback)
  File "/usr/local/pytis/lib/pytis/data/access.py", line 364, in select
   sort=sort, **kwargs)
  File "/usr/local/pytis/lib/pytis/data/postgresql.py", line 3039, in select
   raise_(cls, e, tb)
  File "/usr/local/pytis/lib/pytis/data/postgresql.py", line 3025, in select
   stop_check=stop_check, limit=limit)
  File "/usr/local/pytis/lib/pytis/data/postgresql.py", line 2425, in _pg_select
   self._pg_make_arguments(args, arguments)
  File "/usr/local/pytis/lib/pytis/data/postgresql.py", line 2121, in _pg_make_arguments
   arg_value = arguments.get(b.id(), type_.default_value())
AttributeError: 'NoneType' object has no attribute 'get'