Avoid ListField traceback on closed transaction
When a opening a form cointaining a ListField fails due to a locked record, the
IDLE event causes the traceback below, even though the form instance is
destroyed shortly after opening and actually never gets displayed.

The problem was disovered while solving #71.

Traceback (most recent call last):
  File \"/home/malivanek/git/pytis/lib/pytis/form/event.py\", line 267, in process_event
    result = system_callback()
  File \"/home/malivanek/git/pytis/lib/pytis/form/event.py\", line 212, in system_callback
    result = callback(event)
  File \"/home/malivanek/git/pytis/lib/pytis/form/inputfield.py\", line 1119, in _on_idle
    self._reload_enumeration()
  File \"/home/malivanek/git/pytis/lib/pytis/form/inputfield.py\", line 1710, in _reload_enumeration
    arguments=self._codebook_arguments())
  File \"/home/malivanek/git/pytis/lib/pytis/data/types_.py\", line 3111, in rows
    sort=sort)
  File \"/home/malivanek/git/pytis/lib/pytis/data/data.py\", line 462, in select_map
    self.select(transaction=transaction, **kwargs)
  File \"/home/malivanek/git/pytis/lib/pytis/data/access.py\", line 364, in select
    sort=sort, **kwargs)
  File \"/home/malivanek/git/pytis/lib/pytis/data/postgresql.py\", line 3114, in select
    raise_(cls, e, tb)
  File \"/home/malivanek/git/pytis/lib/pytis/data/postgresql.py\", line 3100, in select
    stop_check=stop_check, limit=limit)
  File \"/home/malivanek/git/pytis/lib/pytis/data/postgresql.py\", line 2493, in _pg_select
    self._pg_query(command.update(args), transaction=transaction_)
  File \"/home/malivanek/git/pytis/lib/pytis/data/postgresql.py\", line 698, in _pg_query
    raise DBUserException(\"Can't use closed transaction\")
DBUserException: (\"Can't use closed transaction\", None)