Rewrite textual clauses to gensql expressions
sqlalchemy 1.3.5 no longer accepts strings as expressions.  Processing the
specification with gsql resulted in:

sqlalchemy.exc.ArgumentError: Textual SQL expression u'' should be explicitly
declared as text(u'')