Fix time field spin up/down
Fixes:

TypeError: unsupported operand type(s) for -=: 'datetime.time' and 'datetime.timedelta'

datetime.time doesn't support addition/subtraction of datetime.timedelta, so we
need to convert it to a datetime first and extract the time part afterwards.