Fix NotImplementedError with sqlalchemy 1.3.5
Calling super class __init__ with sqlalchemy 1.3.5 raises the following
exception:

NotImplementedError: The _PytisAlias class is not intended to be constructed
directly.  Please use the _pytisalias() standalone function or the
_pytisalias() method available from appropriate selectable objects.

Just guessing from sqlalchemy source code, that the code has been moved form
__init__ to _init().  It has been tested, that sqlalchemy 1.3.5 produces the
same result with this fix as sqlalchemy 1.2 did before.