Run idle callback in wx.CallAfter
Prevent "AttributeError: 'Value' object has no attribute '_type'" exception by
postponing callback invocation to the main thread instead of running it
immediately in the wx IDLE thread.