Don't remove file in _open_local_file_viewer
This fixes the traceback:

File "/home/hanak/git/pytis/lib/pytis/extensions/spec.py, line 399, in printdirect()
    time.sleep(1)
File "/usr/lib/python2.7/tempfile.py, line 440, in __exit__()
    self.close()
File "/usr/lib/python2.7/tempfile.py, line 431, in close()
    self.unlink(self.name)
OSError: [Errno 2] Adresář nebo soubor neexistuje: '/tmp/tmppytisqkChBX.pdf'

Removing the file is undesirable at least when _open_local_file_viewer() is
called from open_data_as_file() and when launch_file() is called from
pe.printdirect().  It will be necessary to check the remaining uses of
launch_file() and remove the file afterwards where needed.

Should fix #12.