Don't set vertical alignment on expanded items
Doing so causes the following traceback in wxPython 4.1:

wxAssertionError: C++ assertion \"!(flags & (wxALIGN_BOTTOM |
wxALIGN_CENTRE_VERTICAL))\" failed at
/home/wxpy/wxPython-4.1.0/ext/wxWidgets/src/common/sizer.cpp(2114) in
DoInsert(): Vertical alignment flags are ignored with wxEXPAND