Attempt to avoid RuntimeError in field validation
We are getting such tracebacks lately:

Traceback (most recent call last):
  File "/usr/local/virtualenvs/pytis_wx4/local/lib/python2.7/site-packages/wx/core.py", line 3259, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/local/pytis/lib/pytis/form/inputfield.py", line 495, in _do_validation
    error = self._validate()
  File "/usr/local/pytis/lib/pytis/form/inputfield.py", line 480, in _validate
    return self._row.validate(self.id(), self._get_value())
  File "/usr/local/pytis/lib/pytis/form/inputfield.py", line 963, in _get_value
    return self._ctrl.GetValue()
RuntimeError: wrapped C/C++ object of type TextCtrl has been deleted

I assume this is because of calling _do_validation through wx.CallAfter().