Update grid tooltip in wx.CallAfter
Prevent "AttributeError: 'Record' object has no attribute '_coldict'" exception
by postponing record access to the main thread instead of running it
immediately in the wx IDLE thread.