Work around 'gsql pytis.dbdefs' problem
The previous commit 7e8e9b438 "Make gsql pytis.dbdefs work" caused problems
when generaating SQL in applications:

pytis.data.gensqlalchemy.SQLException: ('Duplicate object name', (<class
'ecomps.dbdefs.db_dmp_roles.EVPytisUserRoles'>, {<class
'pytis.dbdefs.db_pytis_menu.EvPytisUserRoles'>}))

So we can't import all submodules unconditionally.  Thus the hack: Import them
only when 'gsql pytis.dbdefs' is invoked...