Set SQLRaw key to avoid TypeError
Leaving None in the 'key' attribute causes TypeError within
_metadata.sorted_tables in Python 3:

Traceback (most recent call last):
  File "../pytis/tools/gsql.py", line 98, in <module>
    run()
  File "../pytis/tools/gsql.py", line 94, in run
    limit_module=options.limit_module)
  File "/Users/cerha/work/pytis/lib/pytis/data/gensqlalchemy.py", line 4438, in gsql_module
    config_file, upgrade, debug, (module_name if limit_module else None))
  File "/Users/cerha/work/pytis/lib/pytis/data/gensqlalchemy.py", line 4125, in _gsql_process
    upgrade_metadata, module_name)
  File "/Users/cerha/work/pytis/lib/pytis/data/gensqlalchemy.py", line 4258, in _gsql_process_1
    for table in _metadata.sorted_tables:
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4115, in sorted_tables
    sorted(self.tables.values(), key=lambda t: t.key)
TypeError: '<' not supported between instances of 'NoneType' and 'str'