Avoid gsql TypeError when --pretty is not set
The default value of the --pretty option was None which caused the following
error in Python 3:

Traceback (most recent call last):
  File "../pytis/tools/gsql.py", line 98, in <module>
    run()
  File "../pytis/tools/gsql.py", line 94, in run
    limit_module=options.limit_module)
  File "/Users/cerha/work/pytis/lib/pytis/data/gensqlalchemy.py", line 4437, in gsql_module
    config_file, upgrade, debug, (module_name if limit_module else None))
  File "/Users/cerha/work/pytis/lib/pytis/data/gensqlalchemy.py", line 4124, in _gsql_process
    upgrade_metadata, module_name)
  File "/Users/cerha/work/pytis/lib/pytis/data/gensqlalchemy.py", line 4263, in _gsql_process_1
    table.pytis_upgrade(upgrade_metadata)
  File "/Users/cerha/work/pytis/lib/pytis/data/gensqlalchemy.py", line 1610, in pytis_upgrade
    if not self._pytis_upgrade(metadata):
  File "/Users/cerha/work/pytis/lib/pytis/data/gensqlalchemy.py", line 1971, in _pytis_upgrade
    self.pytis_create()
  File "/Users/cerha/work/pytis/lib/pytis/data/gensqlalchemy.py", line 1595, in pytis_create
    self.create(_engine, checkfirst=False)
  File "/Users/cerha/work/pytis/lib/pytis/data/gensqlalchemy.py", line 3065, in create
    bind._run_visitor(_PytisSchemaGenerator, self, checkfirst=checkfirst)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 312, in _run_visitor
    element
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 138, in traverse_single
    return meth(obj, **kw)
  File "/Users/cerha/work/pytis/lib/pytis/data/gensqlalchemy.py", line 170, in visit_view
    with local_search_path(self._set_search_path(view.search_path())):
  File "/Users/cerha/work/pytis/lib/pytis/data/gensqlalchemy.py", line 160, in _set_search_path
    self.connection.execute(command)
  File "/Users/cerha/work/pytis/lib/pytis/data/gensqlalchemy.py", line 4050, in _dump_sql_command
    if _pretty > 1:
TypeError: '>' not supported between instances of 'NoneType' and 'int'