Avoid UI event tracebacks
The UI event sometimes fails in _current_key() with AttributeError: 'Value'
object has no attribute '_value'.  This seems to be a threading issue, but in
this case it can be simply avoided by using self.current_row() instead of
_current_key(), because we just test the result for None and don't actually
need the key values at all.