Fix codebook widget construction
The previous implementation caused the following error in wxPython 4.1:

wxAssertionError: C++ assertion \"\"!m_containingSizer\"\" failed at
/home/wxpy/wxPython-4.1.0/ext/wxWidgets/src/common/wincmn.cpp(2490) in
SetContainingSizer(): Adding a window already in a sizer, detach it first!

We must combine the sizer created in the parent class method with the new
sizer - not ignore the parent sizer.