Perform field validation in the main thread
Avoid "AttributeError: 'Operator' object has no attribute '_name'" caused by
accessing uninitialized objects in the IDLE thread by postponing validation to
the main thread.